import pandas as pd
from pymongo import MongoClient

# Read data from the CSV file
df = pd.read_csv('pokemon.csv')
# print(df)


# Convert DataFrame to a list of dictionaries
documents = df.to_dict(orient='records')
# print(documents)

# Connect to MongoDB
mongoClient = MongoClient("mongodb://localhost/pokemon")
pokemonDB = mongoClient['pokemondb']
pokemonColl = pokemonDB['pokemon_data']

# Insert the documents into the collection with error handling
for i, doc in enumerate(documents):
    print(f"Inserting document {i+1}/{len(documents)}")
    pokemonColl.insert_one(doc)


print(f"Inserted {len(documents)} documents")

print("Data insertion complete!")

use pokemon
switched to db pokemon
pokemon> db.pokemons.find().pretty()
[
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7abd"),
    abilities: "['Overgrow', 'Chlorophyll']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 0.5,
    against_fairy: 0.5,
    against_fight: 0.5,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 1,
    against_ice: 2,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 2,
    against_rock: 1,
    against_steel: 1,
    against_water: 0.5,
    attack: 49,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 318,
    capture_rate: '45',
    classfication: 'Seed Pokémon',
    defense: 49,
    experience_growth: 1059860,
    height_m: 0.7,
    hp: 45,
    name: 'Bulbasaur',
    percentage_male: 88.1,
    pokedex_number: 1,
    sp_attack: 65,
    sp_defense: 65,
    speed: 45,
    type1: 'grass',
    type2: 'poison',
    weight_kg: 6.9,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7abe"),
    abilities: "['Overgrow', 'Chlorophyll']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 0.5,
    against_fairy: 0.5,
    against_fight: 0.5,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 1,
    against_ice: 2,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 2,
    against_rock: 1,
    against_steel: 1,
    against_water: 0.5,
    attack: 62,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 405,
    capture_rate: '45',
    classfication: 'Seed Pokémon',
    defense: 63,
    experience_growth: 1059860,
    height_m: 1,
    hp: 60,
    name: 'Ivysaur',
    percentage_male: 88.1,
    pokedex_number: 2,
    sp_attack: 80,
    sp_defense: 80,
    speed: 60,
    type1: 'grass',
    type2: 'poison',
    weight_kg: 13,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7abf"),
    abilities: "['Overgrow', 'Chlorophyll']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 0.5,
    against_fairy: 0.5,
    against_fight: 0.5,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 1,
    against_ice: 2,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 2,
    against_rock: 1,
    against_steel: 1,
    against_water: 0.5,
    attack: 100,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 625,
    capture_rate: '45',
    classfication: 'Seed Pokémon',
    defense: 123,
    experience_growth: 1059860,
    height_m: 2,
    hp: 80,
    name: 'Venusaur',
    percentage_male: 88.1,
    pokedex_number: 3,
    sp_attack: 122,
    sp_defense: 120,
    speed: 80,
    type1: 'grass',
    type2: 'poison',
    weight_kg: 100,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac0"),
    abilities: "['Blaze', 'Solar Power']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 0.5,
    against_fight: 1,
    against_fire: 0.5,
    against_flying: 1,
    against_ghost: 1,
    against_grass: 0.5,
    against_ground: 2,
    against_ice: 0.5,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 2,
    against_steel: 0.5,
    against_water: 2,
    attack: 52,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 309,
    capture_rate: '45',
    classfication: 'Lizard Pokémon',
    defense: 43,
    experience_growth: 1059860,
    height_m: 0.6,
    hp: 39,
    name: 'Charmander',
    percentage_male: 88.1,
    pokedex_number: 4,
    sp_attack: 60,
    sp_defense: 50,
    speed: 65,
    type1: 'fire',
    type2: NaN,
    weight_kg: 8.5,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac1"),
    abilities: "['Blaze', 'Solar Power']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 0.5,
    against_fight: 1,
    against_fire: 0.5,
    against_flying: 1,
    against_ghost: 1,
    against_grass: 0.5,
    against_ground: 2,
    against_ice: 0.5,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 2,
    against_steel: 0.5,
    against_water: 2,
    attack: 64,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 405,
    capture_rate: '45',
    classfication: 'Flame Pokémon',
    defense: 58,
    experience_growth: 1059860,
    height_m: 1.1,
    hp: 58,
    name: 'Charmeleon',
    percentage_male: 88.1,
    pokedex_number: 5,
    sp_attack: 80,
    sp_defense: 65,
    speed: 80,
    type1: 'fire',
    type2: NaN,
    weight_kg: 19,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac2"),
    abilities: "['Blaze', 'Solar Power']",
    against_bug: 0.25,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 0.5,
    against_fight: 0.5,
    against_fire: 0.5,
    against_flying: 1,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 0,
    against_ice: 1,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 4,
    against_steel: 0.5,
    against_water: 2,
    attack: 104,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 634,
    capture_rate: '45',
    classfication: 'Flame Pokémon',
    defense: 78,
    experience_growth: 1059860,
    height_m: 1.7,
    hp: 78,
    name: 'Charizard',
    percentage_male: 88.1,
    pokedex_number: 6,
    sp_attack: 159,
    sp_defense: 115,
    speed: 100,
    type1: 'fire',
    type2: 'flying',
    weight_kg: 90.5,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac3"),
    abilities: "['Torrent', 'Rain Dish']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 1,
    against_fight: 1,
    against_fire: 0.5,
    against_flying: 1,
    against_ghost: 1,
    against_grass: 2,
    against_ground: 1,
    against_ice: 0.5,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 1,
    against_steel: 0.5,
    against_water: 0.5,
    attack: 48,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 314,
    capture_rate: '45',
    classfication: 'Tiny Turtle Pokémon',
    defense: 65,
    experience_growth: 1059860,
    height_m: 0.5,
    hp: 44,
    name: 'Squirtle',
    percentage_male: 88.1,
    pokedex_number: 7,
    sp_attack: 50,
    sp_defense: 64,
    speed: 43,
    type1: 'water',
    type2: NaN,
    weight_kg: 9,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac4"),
    abilities: "['Torrent', 'Rain Dish']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 1,
    against_fight: 1,
    against_fire: 0.5,
    against_flying: 1,
    against_ghost: 1,
    against_grass: 2,
    against_ground: 1,
    against_ice: 0.5,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 1,
    against_steel: 0.5,
    against_water: 0.5,
    attack: 63,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 405,
    capture_rate: '45',
    classfication: 'Turtle Pokémon',
    defense: 80,
    experience_growth: 1059860,
    height_m: 1,
    hp: 59,
    name: 'Wartortle',
    percentage_male: 88.1,
    pokedex_number: 8,
    sp_attack: 65,
    sp_defense: 80,
    speed: 58,
    type1: 'water',
    type2: NaN,
    weight_kg: 22.5,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac5"),
    abilities: "['Torrent', 'Rain Dish']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 1,
    against_fight: 1,
    against_fire: 0.5,
    against_flying: 1,
    against_ghost: 1,
    against_grass: 2,
    against_ground: 1,
    against_ice: 0.5,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 1,
    against_steel: 0.5,
    against_water: 0.5,
    attack: 103,
    base_egg_steps: 5120,
    base_happiness: 70,
    base_total: 630,
    capture_rate: '45',
    classfication: 'Shellfish Pokémon',
    defense: 120,
    experience_growth: 1059860,
    height_m: 1.6,
    hp: 79,
    name: 'Blastoise',
    percentage_male: 88.1,
    pokedex_number: 9,
    sp_attack: 135,
    sp_defense: 115,
    speed: 78,
    type1: 'water',
    type2: NaN,
    weight_kg: 85.5,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac6"),
    abilities: "['Shield Dust', 'Run Away']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 1,
    against_fight: 0.5,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.5,
    against_ground: 0.5,
    against_ice: 1,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 30,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 195,
    capture_rate: '255',
    classfication: 'Worm Pokémon',
    defense: 35,
    experience_growth: 1000000,
    height_m: 0.3,
    hp: 45,
    name: 'Caterpie',
    percentage_male: 50,
    pokedex_number: 10,
    sp_attack: 20,
    sp_defense: 20,
    speed: 45,
    type1: 'bug',
    type2: NaN,
    weight_kg: 2.9,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac7"),
    abilities: "['Shed Skin']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 1,
    against_fight: 0.5,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.5,
    against_ground: 0.5,
    against_ice: 1,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 20,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 205,
    capture_rate: '120',
    classfication: 'Cocoon Pokémon',
    defense: 55,
    experience_growth: 1000000,
    height_m: 0.7,
    hp: 50,
    name: 'Metapod',
    percentage_male: 50,
    pokedex_number: 11,
    sp_attack: 25,
    sp_defense: 25,
    speed: 30,
    type1: 'bug',
    type2: NaN,
    weight_kg: 9.9,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac8"),
    abilities: "['Compoundeyes', 'Tinted Lens']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 1,
    against_fight: 0.25,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 0,
    against_ice: 2,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 4,
    against_steel: 1,
    against_water: 1,
    attack: 45,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 395,
    capture_rate: '45',
    classfication: 'Butterfly Pokémon',
    defense: 50,
    experience_growth: 1000000,
    height_m: 1.1,
    hp: 60,
    name: 'Butterfree',
    percentage_male: 50,
    pokedex_number: 12,
    sp_attack: 90,
    sp_defense: 80,
    speed: 70,
    type1: 'bug',
    type2: 'flying',
    weight_kg: 32,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ac9"),
    abilities: "['Shield Dust', 'Run Away']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 0.5,
    against_fight: 0.25,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 1,
    against_ice: 1,
    against_normal: 1,
    against_poison: 0.5,
    against_psychic: 2,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 35,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 195,
    capture_rate: '255',
    classfication: 'Hairy Pokémon',
    defense: 30,
    experience_growth: 1000000,
    height_m: 0.3,
    hp: 40,
    name: 'Weedle',
    percentage_male: 50,
    pokedex_number: 13,
    sp_attack: 20,
    sp_defense: 20,
    speed: 50,
    type1: 'bug',
    type2: 'poison',
    weight_kg: 3.2,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7aca"),
    abilities: "['Shed Skin']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 0.5,
    against_fight: 0.25,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 1,
    against_ice: 1,
    against_normal: 1,
    against_poison: 0.5,
    against_psychic: 2,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 25,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 205,
    capture_rate: '120',
    classfication: 'Cocoon Pokémon',
    defense: 50,
    experience_growth: 1000000,
    height_m: 0.6,
    hp: 45,
    name: 'Kakuna',
    percentage_male: 50,
    pokedex_number: 14,
    sp_attack: 25,
    sp_defense: 25,
    speed: 35,
    type1: 'bug',
    type2: 'poison',
    weight_kg: 10,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7acb"),
    abilities: "['Swarm', 'Sniper']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 0.5,
    against_fight: 0.25,
    against_fire: 2,
    against_flying: 2,
    against_ghost: 1,
    against_grass: 0.25,
    against_ground: 1,
    against_ice: 1,
    against_normal: 1,
    against_poison: 0.5,
    against_psychic: 2,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 150,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 495,
    capture_rate: '45',
    classfication: 'Poison Bee Pokémon',
    defense: 40,
    experience_growth: 1000000,
    height_m: 1,
    hp: 65,
    name: 'Beedrill',
    percentage_male: 50,
    pokedex_number: 15,
    sp_attack: 15,
    sp_defense: 80,
    speed: 145,
    type1: 'bug',
    type2: 'poison',
    weight_kg: 29.5,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7acc"),
    abilities: "['Keen Eye', 'Tangled Feet', 'Big Pecks']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 1,
    against_fight: 1,
    against_fire: 1,
    against_flying: 1,
    against_ghost: 0,
    against_grass: 0.5,
    against_ground: 0,
    against_ice: 2,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 45,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 251,
    capture_rate: '255',
    classfication: 'Tiny Bird Pokémon',
    defense: 40,
    experience_growth: 1059860,
    height_m: 0.3,
    hp: 40,
    name: 'Pidgey',
    percentage_male: 50,
    pokedex_number: 16,
    sp_attack: 35,
    sp_defense: 35,
    speed: 56,
    type1: 'normal',
    type2: 'flying',
    weight_kg: 1.8,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7acd"),
    abilities: "['Keen Eye', 'Tangled Feet', 'Big Pecks']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 1,
    against_fight: 1,
    against_fire: 1,
    against_flying: 1,
    against_ghost: 0,
    against_grass: 0.5,
    against_ground: 0,
    against_ice: 2,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 60,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 349,
    capture_rate: '120',
    classfication: 'Bird Pokémon',
    defense: 55,
    experience_growth: 1059860,
    height_m: 1.1,
    hp: 63,
    name: 'Pidgeotto',
    percentage_male: 50,
    pokedex_number: 17,
    sp_attack: 50,
    sp_defense: 50,
    speed: 71,
    type1: 'normal',
    type2: 'flying',
    weight_kg: 30,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ace"),
    abilities: "['Keen Eye', 'Tangled Feet', 'Big Pecks']",
    against_bug: 0.5,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 2,
    against_fairy: 1,
    against_fight: 1,
    against_fire: 1,
    against_flying: 1,
    against_ghost: 0,
    against_grass: 0.5,
    against_ground: 0,
    against_ice: 2,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 2,
    against_steel: 1,
    against_water: 1,
    attack: 80,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 579,
    capture_rate: '45',
    classfication: 'Bird Pokémon',
    defense: 80,
    experience_growth: 1059860,
    height_m: 1.5,
    hp: 83,
    name: 'Pidgeot',
    percentage_male: 50,
    pokedex_number: 18,
    sp_attack: 135,
    sp_defense: 80,
    speed: 121,
    type1: 'normal',
    type2: 'flying',
    weight_kg: 39.5,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7acf"),
    abilities: "['Run Away', 'Guts', 'Hustle', 'Gluttony', 'Hustle', 'Thick Fat']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 1,
    against_fight: 2,
    against_fire: 1,
    against_flying: 1,
    against_ghost: 0,
    against_grass: 1,
    against_ground: 1,
    against_ice: 1,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 1,
    against_steel: 1,
    against_water: 1,
    attack: 56,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 253,
    capture_rate: '255',
    classfication: 'Mouse Pokémon',
    defense: 35,
    experience_growth: 1000000,
    height_m: NaN,
    hp: 30,
    name: 'Rattata',
    percentage_male: 50,
    pokedex_number: 19,
    sp_attack: 25,
    sp_defense: 35,
    speed: 72,
    type1: 'normal',
    type2: 'dark',
    weight_kg: NaN,
    generation: 1,
    is_legendary: 0
  },
  {
    _id: ObjectId("645d7ca88a5fbb3f91ba7ad0"),
    abilities: "['Run Away', 'Guts', 'Hustle', 'Gluttony', 'Hustle', 'Thick Fat']",
    against_bug: 1,
    against_dark: 1,
    against_dragon: 1,
    against_electric: 1,
    against_fairy: 1,
    against_fight: 2,
    against_fire: 1,
    against_flying: 1,
    against_ghost: 0,
    against_grass: 1,
    against_ground: 1,
    against_ice: 1,
    against_normal: 1,
    against_poison: 1,
    against_psychic: 1,
    against_rock: 1,
    against_steel: 1,
    against_water: 1,
    attack: 71,
    base_egg_steps: 3840,
    base_happiness: 70,
    base_total: 413,
    capture_rate: '127',
    classfication: 'Mouse Pokémon',
    defense: 70,
    experience_growth: 1000000,
    height_m: NaN,
    hp: 75,
    name: 'Raticate',
    percentage_male: 50,
    pokedex_number: 20,
    sp_attack: 40,
    sp_defense: 80,
    speed: 77,
    type1: 'normal',
    type2: 'dark',
    weight_kg: NaN,
    generation: 1,
    is_legendary: 0
  }
]
Type "it" for more

